--Q1. What is the total revenue generated by male vs. female customers?
SELECT
	GENDER,
	ROUND(
		100.0 * SUM(PURCHASE_AMOUNT_USD) / SUM(SUM(PURCHASE_AMOUNT_USD)) OVER (),
		2
	) AS PERCENTAGE_SHARE
FROM
	CUSTOMER
GROUP BY
	GENDER;

--Q2. Top purchase category of each age group by revenue
WITH
	CATEGORY_REVENUE AS (
		SELECT
			AGE_GROUP,
			CATEGORY,
			SUM(PURCHASE_AMOUNT_USD) AS REVENUE
		FROM
			CUSTOMER
		GROUP BY
			AGE_GROUP,
			CATEGORY
	),
	RANKED_CATEGORIES AS (
		SELECT
			AGE_GROUP,
			CATEGORY,
			REVENUE,
			RANK() OVER (
				PARTITION BY
					AGE_GROUP
				ORDER BY
					REVENUE DESC
			) AS RNK
		FROM
			CATEGORY_REVENUE
	)
SELECT
	AGE_GROUP,
	CATEGORY,
	REVENUE
FROM
	RANKED_CATEGORIES
WHERE
	RNK = 1
ORDER BY
	AGE_GROUP;

-- Q2. Top purchase category of each age group by number of purchases
WITH
	CATEGORY_COUNTS AS (
		SELECT
			AGE_GROUP,
			CATEGORY,
			COUNT(*) AS PURCHASE_COUNT
		FROM
			CUSTOMER
		GROUP BY
			AGE_GROUP,
			CATEGORY
	),
	RANKED_CATEGORIES AS (
		SELECT
			AGE_GROUP,
			CATEGORY,
			PURCHASE_COUNT,
			RANK() OVER (
				PARTITION BY
					AGE_GROUP
				ORDER BY
					PURCHASE_COUNT DESC
			) AS RNK
		FROM
			CATEGORY_COUNTS
	)
SELECT
	AGE_GROUP,
	CATEGORY,
	PURCHASE_COUNT
FROM
	RANKED_CATEGORIES
WHERE
	RNK = 1
ORDER BY
	AGE_GROUP;

-- Q3. Which are the top 5 products with the highest average review rating?
WITH
	AVG_REVIEW_RATING AS (
		SELECT
			ITEM_PURCHASED,
			ROUND(AVG(REVIEW_RATING), 2) AS AVG_RATING,
			RANK() OVER (
				ORDER BY
					AVG(REVIEW_RATING) DESC
			) RNK
		FROM
			CUSTOMER
		GROUP BY
			ITEM_PURCHASED
	)
SELECT
	ITEM_PURCHASED,
	AVG_RATING
FROM
	AVG_REVIEW_RATING
WHERE
	RNK <= 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT
	SHIPPING_TYPE,
	ROUND(AVG(PURCHASE_AMOUNT_USD), 2) AS AVG_PURCHASE_AMT
FROM
	CUSTOMER
GROUP BY
	SHIPPING_TYPE
ORDER BY
	AVG_PURCHASE_AMT DESC;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
WITH
	CUSTOMER_SUBSCRIPTION AS (
		SELECT
			CASE
				WHEN SUBSCRIPTION_STATUS = 'Yes' THEN 'Subscriber'
				ELSE 'Non-Subscriber'
			END AS CUSTOMER_STATUS,
			PURCHASE_AMOUNT_USD
		FROM
			CUSTOMER
	)
SELECT
	CUSTOMER_STATUS,
	ROUND(AVG(PURCHASE_AMOUNT_USD), 2),
	SUM(PURCHASE_AMOUNT_USD)
FROM
	CUSTOMER_SUBSCRIPTION
GROUP BY
	CUSTOMER_STATUS;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
	ITEM_PURCHASED,
	ROUND(
		100.0 * SUM(
			CASE
				WHEN DISCOUNT_APPLIED = 'Yes' THEN 1
				ELSE 0
			END
		) / COUNT(*),
		2
	) AS PERCENTAGE
FROM
	CUSTOMER
GROUP BY
	ITEM_PURCHASED
ORDER BY
	PERCENTAGE DESC
LIMIT
	5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT
	CUSTOMER_SEGMENT,
	COUNT(*)
FROM
	(
		SELECT
			CASE
				WHEN PREVIOUS_PURCHASES < 1 THEN 'New'
				WHEN PREVIOUS_PURCHASES BETWEEN 1 AND 10  THEN 'Returning'
				ELSE 'Loyal'
			END AS CUSTOMER_SEGMENT
		FROM
			CUSTOMER
	) C
GROUP BY
	CUSTOMER_SEGMENT;

--Q8. What are the top 3 most purchased products within each category? 
WITH
	TOP_PRODUCT_PURCHASES AS (
		SELECT
			CATEGORY,
			ITEM_PURCHASED,
			COUNT(*) AS ORDER_NUM,
			ROW_NUMBER() OVER (
				PARTITION BY
					CATEGORY
				ORDER BY
					COUNT(*) DESC
			) AS ITEM_RANK
		FROM
			CUSTOMER
		GROUP BY
			CATEGORY,
			ITEM_PURCHASED
	)
SELECT
	CATEGORY,
	ITEM_PURCHASED,
	ITEM_RANK
FROM
	TOP_PRODUCT_PURCHASES
WHERE
	ITEM_RANK <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
	SUBSCRIPTION_STATUS,
	COUNT(*)
FROM
	CUSTOMER
WHERE
	PREVIOUS_PURCHASES > 5
GROUP BY
	SUBSCRIPTION_STATUS;

--Q10. What is the revenue contribution of each age group? 
SELECT
	AGE_GROUP,
	ROUND(
		100.0 * SUM(PURCHASE_AMOUNT_USD) / SUM(SUM(PURCHASE_AMOUNT_USD)) OVER (),
		2
	) AS PERCENTAGE_SHARE
FROM
	CUSTOMER
GROUP BY
	AGE_GROUP
ORDER BY
	PERCENTAGE_SHARE DESC;